# Generated by Django 5.1.7 on 2025-03-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_orderplaced_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
