# Generated by Django 5.1.6 on 2025-03-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_discount_price_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
